
/oak:
    camera_i_enable_imu: true
    camera_i_enable_ir: false
    camera_i_nn_type: none
    camera_i_pipeline_type: rgbtof
    pipeline_gen_i_enable_sync: true
    right_i_low_bandwidth: true
    right_i_synced: true
    tof_i_synced: true
