/oak:
  camera_i_nn_type: spatial
  rgb_i_enable_preview: true
  rgb_i_keep_preview_aspect_ratio: false
  nn_i_enable_passthrough: true
  nn_i_disable_resize: true
  stereo_i_subpixel: true
/spatial_bb_node:
  desqueeze: true
# /oak:
#   ros__parameters:
#     camera:
#       i_nn_type: spatial
#     rgb:
#       i_enable_preview: true
#       i_keep_preview_aspect_ratio: false
#     nn:
#       i_enable_passthrough: true
#       i_disable_resize: true
#     stereo:
#       i_subpixel: true
# /spatial_bb_node:
#   ros__parameters:
#     desqueeze: true

